### ISSUE TITLE
[Feature] Option to teleport tokens instead of moving them with keybind

### ISSUE THREAD

**Issue by guganda** [thatlonelybugbear/token-warp#2]
Switch between moving/teleporting tokens on keybind so that the token won't trigger undesired template/MATT/terrain effects.

Aditional suggestion: make this configuration be unique to players and npcs tokens, so that you can choose whether the default warping is teleport or move to different types of tokens. (default move npc, default tp player, for instance, and switch them on keybind)

**Comment by dineshm72** [comment]
My preference would be to be able to set whether it should teleport or move automatically, not require a keybind to get a teleport.

I want my moves to be a teleport always.  I am typically using it when I am repositioning a PC from one part of the map to another (maybe they were afk for a bit, maybe they missed last session, etc.).  I never want them triggering anything while moving, I just want them to appear in the place I've dragged them.

Requiring a keybind to get this behavior is adding back the issue that was the whole reason I requested this code/module in the first place - I don't want to have to remember to use a modifier key to get a teleport and avoid having the token animate across the map or trigger things along the way.

**Comment by thatlonelybugbear** [comment]
Alright, will go over these during the weekend! I will definitely try to include both options!

**Comment by guganda** [comment]
It could be a keybind to toggle between options, instead of being a hold/release keybind.

**Comment by thatlonelybugbear** [comment]
Long time no see.

Made a PR in [MATT](https://github.com/ironmonk88/monks-active-tiles/pull/668) to allow better integration, cause any other way I was going about, caused issues with Drag Ruler's integration.

Should be out as soon as MATT updates (and if) 🤞 

My initial thinking was a boolean setting to bypass MATT triggers if the Token Warp cancels movement animation.

If needed, I could support also a keybind to override, but at that point, I would say that Drag Ruler's teleport keybind works too (at least for most users which in my mind use Drag Ruler).

WDYT? 🤔

**Comment by thatlonelybugbear** [comment]
Next MATT release will make sure that when a `preUpdateToken` hooks passes `animate: false`, no Tiles will be triggered by that "movement".

**Comment by thatlonelybugbear** [comment]
MATT 11.18 handles interaction with modules which for any reason pass a `animate:false` parameter in the `preUpdateToken` dnd5e hook, better.

When that parameter is encountered, MATT will disallow triggering of tiles in the path of the dragged tokens.

Slight change to the logic of `Disable token animation movement by default` is therefore needed, as with that setting now on, no MATT whatsoever can be triggered.

I will probably rework that setting to only affect dragging tokens around the map, whereas using the keyboard for moving will trigger tiles normally.
