### ISSUE TITLE
Support for non D&D 5e Systems

### ISSUE THREAD

**Issue by maplealmond** [thatlonelybugbear/token-warp#9]
This is a pretty universally useful mod, and it's a shame its been locked to D&D 5e only.  Would you consider changing the relationship to include other common systems, or even no systems?

**Comment by thatlonelybugbear** [comment]
Certainly I can do that. I haven't used any other systems, so I am not sure of any specifics, but as I am just using the core hooks, I think it's pretty safe.

I will do that promptly and if users of other systems could test and make sure nothing is off or let me know if something needs to be checked, it would be greatly appreciated.

**Comment by thatlonelybugbear** [comment]
v11.2.0 should allow other systems to use Token Warp too :)
